language: python           
jobs:
  include:
      language: python
      python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"      # current default Python on Travis CI
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.9-dev"  # 3.9 development branch
    - "nightly"  # nightly build
    - name: "Python 3.7.4 on macOS"
      os: osx
  
      env:
   - DJANGO_VERSION=2.1.13
   - DJANGO_VERSION=2.2.6

script: python3 my_app.py || python my_app.py
