language: python           
jobs:
  include:
      language: python
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  
      env:
   - DJANGO_VERSION=2.1.13
   - DJANGO_VERSION=2.2.6

script: python3 my_app.py || python my_app.py
