# Generated by Django 4.0.4 on 2022-04-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_myweb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myweb',
        ),
        migrations.RemoveField(
            model_name='person',
            name='BirthDate',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Sex',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
    ]
